version: "3.8"

services:
  postgres:
    container_name: slim-fairy-postgres
    image: postgres:14.6
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  slim-fairy-service:
    container_name: slim-fairy-service
    build: .
    depends_on:
      - postgres
    command: ./service
    ports:
      - 8080:8080
    environment:
      PG_DSN: ${PG_DSN}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
