version: "3.8"

services:
  postgres:
    container_name: slim-fairy-postgres
    image: postgres:15.1
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
