version: '3.7'

services:

# run this to create external network:
# docker network create traefiknet

# run container:
# touch acme.json
# chmod 600 acme.json
# docker-compose up -d traefik

# show logs:
# docker-compose logs -f

  traefik:
    image: traefik:v2.2
    restart: always
    container_name: "traefik"
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --accesslog=true
      - --metrics.prometheus=true
      - --entrypoints.metrics.address=:8081
      - --metrics.prometheus.entrypoint=metrics
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/config/traefik/traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - /data/config/ssl/live/bot.lorlovdev.ru:/etc/traefik/bot.lorlovdev.ru
      - /data/config/ssl/live/*.bot.lorlovdev.ru:/etc/traefik/*.bot.lorlovdev.ru
    networks:
      - traefiknet

networks:
  traefiknet:
    external: true
    name: traefiknet
