version: '3.7'

services:

  # docs: https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/

  # run this to create external network:
  # docker network create traefiknet

  # run container:
  # docker-compose up -d

  # show logs:
  # docker-compose logs -f

  # stop container:
  # docker-compose down

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      # FOR DEBUG
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # FOR DEBUG
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=lev.orlov.dev@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefiknet

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      # FOR HTTP
      - "traefik.http.routers.whoami-http.entrypoints=web"
      - "traefik.http.routers.whoami-http.rule=Host(`whoami.lorlovdev.ru`)"
      # REDIRECT HTTP TO HTTPS
      - "traefik.http.routers.whoami-http.middlewares=whoami-https"
      - "traefik.http.middlewares.whoami-https.redirectscheme.scheme=https"
      # FOR HTTPS
      - "traefik.http.routers.whoami.rule=Host(`whoami.lorlovdev.ru`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    networks:
      - traefiknet

networks:
  traefiknet:
    external: true
    name: traefiknet
