// Code generated by "stringer -type=ChatBotDialogStatus"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChatBotDialogStatusInitial-1]
	_ = x[ChatBotDialogStatusInProgress-2]
	_ = x[ChatBotDialogStatusCanceled-3]
	_ = x[ChatBotDialogStatusCompleted-4]
}

const _ChatBotDialogStatus_name = "ChatBotDialogStatusInitialChatBotDialogStatusInProgressChatBotDialogStatusCanceledChatBotDialogStatusCompleted"

var _ChatBotDialogStatus_index = [...]uint8{0, 26, 55, 82, 110}

func (i ChatBotDialogStatus) String() string {
	i -= 1
	if i < 0 || i >= ChatBotDialogStatus(len(_ChatBotDialogStatus_index)-1) {
		return "ChatBotDialogStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ChatBotDialogStatus_name[_ChatBotDialogStatus_index[i]:_ChatBotDialogStatus_index[i+1]]
}
