version: "3.8"

services:

  # run this to create external network:
  # docker network create traefiknet

  postgres:
    container_name: slim-fairy-postgres
    image: postgres:14.6
    ports:
      - "54320:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - slim-fairy-postgres:/var/lib/postgresql/data
    networks:
      - traefiknet

  #  web-service:
  #    container_name: slim-fairy-service
  #    build: .
  #    depends_on:
  #      - postgres
  #    command: /app/server
  #    expose:
  #      - "8080"

  tg-bot:
    container_name: slim-fairy-tg-bot
    build: .
    depends_on:
      - postgres
    command: /app/tg-bot
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tg-bot.rule=Host(`${TG_BOT_WEBHOOK_DOMAIN}`)"
      - "traefik.http.routers.tg-bot.entrypoints=websecure"
      - "traefik.http.routers.tg-bot.tls.certresolver=myresolver"
    networks:
      - traefiknet

volumes:
  slim-fairy-postgres:
    driver: local

networks:
  traefiknet:
    external: true
    name: traefiknet
